name: build and test
on: 
  push:
    tags:
      - environment/*
      - release/*
    branches:
      - feature/*
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.10
      - name: Install
        run: |
          make clean install
      - name: Run unit tests
        run: |
          . .venv/bin/activate
          make unittest

