name: build and test
on: 
  push:
    tags:
      - environment/*
      - release/*
    branches:
      - feature/*
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.10
      - name: Install
        run: |
          make clean install
      - name: Run unit tests
        run: |
          . .venv/bin/activate
          make unittest
      - name: Archive test reports
        if: success() || failure()
        uses: actions/upload-artifact@v2.2.3
        with:
          name: unittest-reports
          path: build/test-reports/html/*
      - name: Publish Test Report
        if: success() || failure()
        uses: mikepenz/action-junit-report@v2
        with:
          check_name: Unit Tests
          report_paths: build/test-reports/unittest.xml
